@host = http://localhost:5000

### Get all weather forecasts (Minimal API)
GET {{host}}/weatherforecast
Accept: application/json

### Get weather forecast by ID (Minimal API)
GET {{host}}/weatherforecast/1
Accept: application/json

### Create new weather forecast (Minimal API)
POST {{host}}/weatherforecast
Content-Type: application/json

{
    "date": "2025-04-16",
    "temperatureC": 25,
    "summary": "Warm"
}
